Header js
front-end-by-rimantas/27-grupe-portfolio-docland pull request #122
Opened 2021-06-08 08:39 UTC by ssinare

2021-06-08 13:04 UTC, igoris12 requested changes

2021-06-08 13:04 UTC, igoris12 commented on js/components/header/Header.js
> +    console.log('close');
console.log('close') reikia ištrinti.

2021-06-08 13:07 UTC, igoris12 commented on js/components/header/Header.js
> +    console.log('close');
![image](https://user-images.githubusercontent.com/82802986/121190203-7b475a00-c873-11eb-8ab1-ea413b1d8afe.png)
logo turetu sumažėti

2021-06-08 13:19 UTC, ssinare commented on js/components/header/Header.js
> +    console.log('close');
console ištrinsiu, nepastebėjau kad liko. Realiai ten dar yra darbu su js. Cia tik etapas, kad butu judejimas
logo originale neturi mazeti. 
Uzdarius inspect laukus hamburgeris nepalenda po logo, buna normaliai

2021-06-09 06:36 UTC, MartinZ96 approved these changes

2021-06-09 07:00 UTC, MarijusIL approved these changes, later dismissed

2021-06-09 10:14 UTC, RomanSaltis submitted a review, later dismissed

2021-06-09 10:22 UTC, MartinZ96 approved these changes, later dismissed

2021-06-09 10:25 UTC, MartinZ96 approved these changes

2021-06-09 10:29 UTC, MarijusIL approved these changes

2021-06-09 10:33 UTC, igoris12 approved these changes

2021-06-09 10:33 UTC, merged