Classes added
front-end-by-rimantas/27-grupe-portfolio-docland pull request #61
Opened 2021-05-26 09:23 UTC by KrisBu

Nesu tikras ar teisingai, ar nereikia dar papildomos class stats contentui?

2021-05-26 10:03 UTC, KrisBu commented
Statistics Layout classes added

2021-05-26 10:42 UTC, MarijusIL approved these changes
lyg ir gerai atrodo

2021-05-26 10:43 UTC, MarijusIL commented on index.html
> +    <div class="Statistics container">
statistics iš mažosios

2021-05-26 10:43 UTC, MarijusIL requested changes
57 eilutėje statistics klasė turi būti iš mažosios

2021-05-27 10:22 UTC, igoris12 approved these changes

2021-05-27 10:22 UTC, MarijusIL approved these changes

2021-05-27 10:23 UTC, RomanSaltis approved these changes

2021-05-27 10:23 UTC, merged