Header classes
front-end-by-rimantas/27-grupe-portfolio-docland pull request #68
Opened 2021-05-26 17:49 UTC by ssinare

2021-05-26 19:58 UTC, MarijusIL requested changes

2021-05-26 19:58 UTC, MarijusIL commented on index.html
> +                <div class="col-lg-10 col-sm-8 col-4">
![image](https://user-images.githubusercontent.com/78425010/119723030-ae521c80-be75-11eb-91b4-67fbb97b0f3a.png)
floatinasi į dešinę su klase: 'reverse-lg' (arba kitais dydžiais)

2021-05-28 08:29 UTC, igoris12 requested changes

2021-05-28 08:29 UTC, igoris12 commented on index.html
> +            <div class="meniu-links col-lg-10 forward-lg col-sm-8 col-4">
col-sm-8, col-4, forward-lg  nereikaling.
col-lg-9, ml-lg-1, reikia pridėti.
.meniu-links perkelti i nouja diva ir css float: right ; 
arba css nieko gali daryti. 
![image](https://user-images.githubusercontent.com/82802986/119954277-7ea33180-bfa7-11eb-87d1-d5e08cda0dd2.png)

2021-05-28 08:29 UTC, igoris12 commented on css/home.css
> +
css gali nieko nedaryti nes nieko stylinti nerike laoute tay, tai darys tas kas daris issuesa su scc style

2021-05-28 08:34 UTC, ssinare commented on css/home.css
> +
Nu zinok jau darau su scc, tai daba nebetrinsiu. Padarysiu responsive, ir hidden. Vakare tureciau pabagti, bo daba biski isleksiu tuoj

2021-05-28 08:45 UTC, ssinare commented on css/home.css
> +
Ir... Ačiū! Aš su tais divais kažkaip dar nesusišneku. bandau trumpesniu kodu prasisukt ir sh... gaunasi. Reiks matyt prie teorijos pargrįžt pasiskaityt

2021-05-29 13:06 UTC, ssinare commented on css/home.css
> +
Pakeitimai zemiau.

2021-05-30 18:32 UTC, igoris12 submitted a review, later dismissed

2021-05-31 10:16 UTC, MarijusIL approved these changes

2021-05-31 10:16 UTC, MartinZ96 approved these changes

2021-05-31 10:16 UTC, igoris12 approved these changes

2021-05-31 10:17 UTC, merged