Footer classes
front-end-by-rimantas/27-grupe-portfolio-docland pull request #69
Opened 2021-05-26 19:07 UTC by ssinare

2021-05-26 19:25 UTC, MarijusIL requested changes
turėtų būti 
![image](https://user-images.githubusercontent.com/78425010/119719156-1eaa6f00-be71-11eb-9f8c-8ae1de6afda3.png)
o yra 
![image](https://user-images.githubusercontent.com/78425010/119719264-3e419780-be71-11eb-8c94-653390ae921c.png)

2021-05-27 14:12 UTC, igoris12 requested changes
as nezinau kodel bet perkelus container class i kita diva viskas pasidaro gerai.
![image](https://user-images.githubusercontent.com/82802986/119841343-63d0ae80-bf0e-11eb-998a-7f64cadbbccc.png)

bet ištrinti nereikaling diva viskas  griuna atgal as nezinau kaip spresti bet tas extra divas nemaiso kaip ir

2021-05-27 18:06 UTC, ssinare commented
> as nezinau kodel bet perkelus container class i kita diva viskas pasidaro gerai.
> ![image](https://user-images.githubusercontent.com/82802986/119841343-63d0ae80-bf0e-11eb-998a-7f64cadbbccc.png)
> 
> bet ištrinti nereikaling diva viskas griuna atgal as nezinau kaip spresti bet tas extra divas nemaiso kaip ir

aciu, atrodo sutvarkiau. idejau bloko klase i ta diva, turetu buti gerai

2021-05-27 18:33 UTC, MarijusIL approved these changes

2021-05-27 18:35 UTC, igoris12 approved these changes

2021-05-28 07:31 UTC, MartinZ96 approved these changes
viskas graziai issidelioja

2021-05-28 07:32 UTC, merged