Course Benefits layout griauciai..
front-end-by-rimantas/27-grupe-portfolio-docland pull request #76
Opened 2021-05-27 10:10 UTC by KrisBu

Ziauriai sunkiai man cia su tais buttonais ir vidiniu info bloku turiniu. Panasu, kad reiks pagalbos..

2021-05-27 13:20 UTC, igoris12 requested changes
tau reikia prideti prie visu kvadratu hidden išskyrus pirma   ir i antra dar pridek visible-md.


![image](https://user-images.githubusercontent.com/82802986/119832636-0b49e300-bf07-11eb-97a9-37f08bd6294f.png)

2021-05-27 13:28 UTC, igoris12 commented on index.html
> +            </div>
visSbile-lg reike 1 s.
visibile-md nereikaling.
reike dar ten pridėti  col-3, ir ml-6 arba geriau col-2 ml-7.

![image](https://user-images.githubusercontent.com/82802986/119834260-77791680-bf08-11eb-9fc2-164da1c01447.png)

2021-05-27 13:30 UTC, igoris12 commented on index.html
> +                    <p>Aenean non accumsan ante. Duis et risus accumsan.</p>
trecia bloka reike prideti visible-lg. 
![image](https://user-images.githubusercontent.com/82802986/119834648-d048af00-bf08-11eb-816b-d33906452568.png)

2021-05-27 13:38 UTC, igoris12 commented on index.html
> +                    <p>Aenean non accumsan ante. Duis et risus accumsan.</p>
jeigu reikės galėsiu rytoj padeti.

2021-05-28 05:55 UTC, KrisBu commented on index.html
> +                    <p>Aenean non accumsan ante. Duis et risus accumsan.</p>
Susitvarkiau viska. Aciu uz pagalba!

2021-05-28 07:45 UTC, igoris12 approved these changes, later dismissed

2021-05-28 08:31 UTC, MartinZ96 requested changes
![image](https://user-images.githubusercontent.com/82806304/119954785-05f0a500-bfa8-11eb-8513-ffdb99d4a6d5.png)
![image](https://user-images.githubusercontent.com/82806304/119954853-19037500-bfa8-11eb-9ae8-a6e57ff62863.png)
ismesk kad rodytu 4 ir bus good
tas 4 bus flexible deadline (lievai nuotraukoj bsk)

2021-05-31 18:13 UTC, RomanSaltis approved these changes, later dismissed

2021-06-01 07:01 UTC, ssinare reviewed
Ar neturetu responsive buti?
![image](https://user-images.githubusercontent.com/82803125/120280361-41e57c00-c2c0-11eb-8590-f2b20e1966fe.png)

2021-06-01 09:01 UTC, MartinZ96 submitted a review, later dismissed

2021-06-03 05:32 UTC, RomanSaltis submitted a review, later dismissed

2021-06-10 10:29 UTC, closed without merging