Price2
front-end-by-rimantas/27-grupe-portfolio-docland pull request #95
Opened 2021-05-28 07:27 UTC by RutaMurav

2021-05-28 08:07 UTC, MartinZ96 requested changes
![image](https://user-images.githubusercontent.com/82806304/119951215-60880200-bfa4-11eb-8141-ba4e38dc3918.png)
![image](https://user-images.githubusercontent.com/82806304/119951405-975e1800-bfa4-11eb-8e22-3755573eeb2e.png)
ta price heading reikia i virsu uzkelt ir jauciu kai uzkelsi turi susitvarkyt ta linija kur antroj foto.

2021-05-28 16:53 UTC, MarijusIL requested changes
prašau, tose skiltyse, kurios nėra tavo _**NEKEISTI**_ nieko.  Absoliučiai nieko.  Nes dabar tu tabuliacijos pridedi visur.

2021-05-28 16:53 UTC, MarijusIL commented on index.html
> +                </div>
ne tavo skiltis, prašau nekeisti nieko

2021-05-28 16:53 UTC, MarijusIL commented on index.html
> +        <!-- Enrol form start -->
ne tavo skiltis, prašau nekeisti nieko

2021-05-28 16:53 UTC, MarijusIL commented on index.html
> +
ne tavo skiltis, prašau nekeisti nieko

2021-05-28 16:53 UTC, MarijusIL commented on index.html
ne tavo skiltis, prašau nekeisti nieko

2021-05-29 09:43 UTC, RutaMurav commented
Zodziu sita mano commita Mentorius padare pataise konflicta tai nezinau jei vistiek blogai tai as pasiduodu.....

2021-05-29 10:53 UTC, MarijusIL commented
> Zodziu sita mano commita Mentorius padare pataise konflicta tai nezinau jei vistiek blogai tai as pasiduodu.....

Radau klaidą - praleidi kale </div> todėl išsiklaipo viskas toliau

2021-06-01 08:55 UTC, closed without merging